### ISSUE TITLE
쿠폰 CRUD

### ISSUE THREAD

**Issue by KATEKEITH** [f-lab-edu/goodchoice#5]
- 쿠폰 생성
- 쿠폰 목록 조회
- 쿠폰 상세 조회
- 쿠폰 수정
- 쿠폰 삭제

- 쿠폰 할인 비즈니스 로직 추가
  - 컬럼에 쿠폰 타입 추가
  - 쿠폰 타입에 따른 할인/차감 금액값 컬럼 추가

**Comment by zzangoobrother** [comment]
- 쿠폰 사용, 취소 로직 추가 완료
